oc_platform_home:
    path:     /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_view:
    path:     /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
#        id: 6
    requirements:
        id: \d+

oc_platform_add:
    path:     /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:     /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:     /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_test:
    path:     /test
    defaults:
        _controller: OCPlatformBundle:Advert:test

oc_platform_purge:
    path:     /purge/{days}
    defaults:
        _controller: OCPlatformBundle:Advert:purge
    requirements:
        days: \d+